@startuml Player Moves Card From Tableau to Tableau
hide empty description 
skinparam linetype polyline

state "**OPEN_GAME**" as OPEN_GAME_INITIAL
state "**OPEN_GAME**" as OPEN_GAME_FINAL

state "**ShowBoard**" as ShowBoard
state c <<choice>> 

note right of c
  The movement is allowed went:
  - lower card of the selected set of cards is one lower
    number than top card of destination pile
end note

state "." as A
state "." as B
state "." as C
state "." as D
state "." as E
state "." as F
state "." as G

OPEN_GAME_INITIAL -down-> A : Player selects Move\nfrom Tableau To Tableau
A -down-> B : System allows to select Tableau pile source
B -down-> C : Player selects Source Foundation pile
C -down-> D : System allows to select number of cards to move
D -down-> E : Player selects number of cards to move
E -down-> c : System allows to select destination Tableau pile
c -down-> F : [allowed]
F -down-> ShowBoard

c -left-> G 
G --> OPEN_GAME_FINAL

ShowBoard -down-> OPEN_GAME_FINAL

@enduml