@startuml Player Moves Card From Waste to Foundation
hide empty description 
skinparam linetype polyline

state "**OPEN_GAME**" as OPEN_GAME_INITIAL
state "**OPEN_GAME**" as OPEN_GAME_FINAL
state "**CLOSED_GAME**" as CLOSED_GAME
state "**ShowBoard**" as ShowBoard
state c <<choice>> 
state d <<choice>> 

note right of c
  Top card of Waste match the following requirements:
  - Is an Ace, or
  - Is one upper than top card of the same suite Pile in Foundation
end note

note left of d
  Foundation is complete 
  when it contains the 
  hole set of cards
end note

state "." as A

OPEN_GAME_INITIAL -down-> c : Player select Move from Waste To Foundation
A -down-> d : [Is Foundation complete]
c -down-> A : [Card matches requirements]
d -down-> ShowBoard : [False]
d -right-> CLOSED_GAME : System informs about\ngame completed
c -right-> OPEN_GAME_FINAL : System informs\nabout Error
ShowBoard -down-> OPEN_GAME_FINAL
@enduml