@startuml Player Moves Card From Foundation to Tableau
hide empty description 
skinparam linetype polyline

state "**OPEN_GAME**" as OPEN_GAME_INITIAL
state "**OPEN_GAME**" as OPEN_GAME_FINAL

state "**ShowBoard**" as ShowBoard
state c <<choice>> 

note right of c
  Top card of selected foundation match the following requirements:
  - Is an King, **or**
  - there is at least one : Is one lower than top card **and** different color of a Tableau pile
end note

state "." as A
state "." as B
state "." as C
state "." as D
state "." as E
state "." as H
state "." as J

OPEN_GAME_INITIAL -down-> A : Player selects Move\nfrom Foundation To Tableau
A -down-> B : System allows to select Foundation pile source
B -down-> C : Player selects Source Foundation pile
C -down-> c : System allows to select Tableau destination pile
c -down-> D : [There is only one valid movement]
c -right-> E : [There are several valid movements]
c -left-> F : [No valid movements are\nposible with the selected card] 

D -down-> ShowBoard
ShowBoard -down-> OPEN_GAME_FINAL
E -down-> H : System allows selection of movement
F -down-> ShowBoard : System shows error

H -down-> J : Player selects which movement wants
J --> ShowBoard

@enduml