@startuml UC_MoveFromTableauToTableau

hide empty description

state c <<choice>>
state d <<choice>>

[*] --> state1 : Player select Move from Tableau To Tableau
state1 --> state2 : System allows to select Card to be moved
state2 --> c : Player selects Card to be moved
c --> ShowError : Invalid card
c --> state3 : Valid card
state3 --> d : System allows to select destination Pile
d --> ShowError : Invalid Destination Pile
ShowError --> [*]
d --> MoveCard : valid destination Pile
MoveCard --> state5 : Show Board
state5 --> [*]

@enduml