@startuml UCAnalysis_FlipDeck
mix_actor Player

package views {
  class GameView
  class MenuView
  class BoardView
  class FoundationView
  class WasteView
  class TableauView
  class DeckView

  GameView *--> BoardView
  GameView *--> MenuView
  BoardView *--> DeckView : <<include>>
  BoardView *--> WasteView : <<include>>
  BoardView *--> FoundationView : <<include>>
  BoardView *--> TableauView : <<include>>
}

package controllers <<Folder>> {
  class FlipCardFromDeckController
}

package models <<Folder>> {
  class Deck
  class Waste
  class Foundation
  class Tableau
  class Card
  Deck -down[hidden]-> Foundation
  Waste -down[hidden]-> Tableau
  Card <.. Deck
  Card <.. Waste
  Card <.. Foundation
  Card <.. Tableau
}

Player -down-> MenuView
MenuView -down[hidden]-> BoardView
MenuView --> FlipCardFromDeckController : execute()
FlipCardFromDeckController --> GameView : show()

FlipCardFromDeckController --> Deck : get()
FlipCardFromDeckController --> Waste : put(Card)

FlipCardFromDeckController ..> Card

BoardView --> MenuView : show()

@enduml