@startuml
mix_actor Player

  package views {
     class MenuView
     class ErrorView
     class GameView
     class BoardView

     GameView *--> BoardView
     note on link: showBoard()
     GameView *--> MenuView
  }

  package controllers {
     class MoveFromTableauToFoundation
  }

  package models {
     class Game
     class Card
     class Foundation
     class Tableau
     Tableau*--> Card
     Foundation*--> Card
     Game *-->Foundation
     Game *-->Tableau
  }

  Player -right-> MenuView
  note on link: Select tableau\nSelect foundation

  MoveFromTableauToFoundation -down-> GameView
  note on link: showBoard()
  MoveFromTableauToFoundation -down-> Game
  note on link: isTableauEmpty()\npopCardFromTableau(tableauId)\nputCardInFoundation(card, foundationId)\npeekCardFromTableau(tableauId)\npeekCardFromFoundation(foundationId)\nisFoundation  Empty(foundationId);

  MoveFromTableauToFoundation  -down-> ErrorView
  note on link: showError()
@enduml
