@startuml UCAnalysis_MoveFromTableauToTableau

mix_actor Player

package views {
    class MenuView
    class ErrorView
    class GameView
    class BoardView

    GameView *--> BoardView
    note on link: showBoard()

    GameView *--> MenuView
}

package controllers {
    class PlayController
    class MoveFromTableauToTableau
    PlayController *-right-> MoveFromTableauToTableau
}

package models {
    class Game
    class Pile
    class Tableau
    Tableau ..> Pile
    Game *-->Tableau
}

PlayController --> GameView
note on link: readAction()


Player -down-> GameView
note on link: Select action\
\nSelect destination\
\nSelect number of cards

MoveFromTableauToTableau --> Game
note on link : getFromPile(n)\nputInPile(n, Card)

MoveFromTableauToTableau --> ErrorView
note on link: showError()

MoveFromTableauToTableau --> GameView 
note on link: showBoard()

ErrorView -left[hidden]-> GameView

@enduml
