@startuml UCAnalysis_MoveFromWasteToFoundation

mix_actor Player

package views {
    class MenuView
    class GameCompleteView
    class ErrorView
    class GameView
    class BoardView

    GameView *--> BoardView
    note on link: showBoard()

    GameView *--> MenuView
    note on link: Select action\nSelect destination
}

package controllers {
    class PlayController
    class MoveFromWasteToFoundation
    PlayController *-right-> MoveFromWasteToFoundation
}

package models {
    class Game
    class Card
    class Waste
    class Foundation
    Waste ..> Card
    Foundation ..> Card
    Game *-->Waste
    Game *-->Foundation
}

MoveFromWasteToFoundation ..> Card

Player -up-> MenuView
note on link: Select action\
\nSelect destination


PlayController --> GameView
note on link: readAction()

MoveFromWasteToFoundation --> ErrorView
note on link: showError()

MoveFromWasteToFoundation --> GameView
note on link: showBoard()

MoveFromWasteToFoundation -down-> Game
note on link: getCardFromWaste()\nisValidCandidateFoundation(Card)\nputInFoundation(Card)\nisFoundationComplete()

MoveFromWasteToFoundation --> GameCompleteView 
note on link: showWinner()

@enduml