@startuml UCAnalysis_MoveFromFoundationToTableau

mix_actor Player

package views {
    class MenuView
    class ErrorView
    class GameView
    class BoardView

    GameView *--> BoardView
    GameView *--> MenuView
}

package controllers {
    class PlayController
    class MoveFromFoundationToTableau
    PlayController *-right-> MoveFromFoundationToTableau
}

package models {
    class Game
    class Card
    class Tableau
    class Foundation
    class Pile

    Game ..> Tableau
    Game ..> Foundation 
    Tableau ..> Pile
    Pile ..> Card
    Foundation ..> Card
    Tableau -right[hidden]-> Foundation
}

Player -up-> GameView
note on link : Select action\
\nSelect origin\
\nSelect destination
GameView -left[hidden]-> Player

note on link : Select action\
\nSelect origin\
\nSelect destination 

PlayController --> GameView
note on link: readAction()

MoveFromFoundationToTableau --> Game
note on link : getCardFromFoundation(n)\
\nputCardInTableau(n, Card)\
\nisValidCandidateInTableau()

MoveFromFoundationToTableau --> ErrorView
note on link : showError()
MoveFromFoundationToTableau --> GameView 
note on link : showBoard()

@enduml