@startuml Analysis Random Movement
mix_actor Player

package views {
    class GameView
    class ErrorView
}

Player -right-> GameView
note on link: Selects Exit

package controllers {
    class PlayController
    class RandomMovementController{
        -generateRandomAction()
    }
    PlayController *-left-> RandomMovementController
}

package models{
    class Game
}

PlayController -up-> GameView
note on link : getAction()

RandomMovementController --> ErrorView
note on link : showError()

RandomMovementController --> Game
note on link: getCardFromWaste()\
\ngetPileSize(n)\
\ngetCardFromPile(n,m)\
\ngetCardFromFoundation(n)\
\nisValidCandidateInPile(n, Card)\
\nisValidCandidateInFoundation(Card)\
\nputCardInFoundation(Card)\
\nputCardInPile(n, Card)

@enduml