@startuml UCAnalysis ReStartGame

mix_actor Player

package views {
  class GameView
  class MenuView
  class ConfirmationView
  GameView --> MenuView
}

package controllers{
    class PlayController
    class RestartGameController
    class StartGameController
    PlayController --> RestartGameController
}

Player -left-> GameView
note on link: Select action

RestartGameController --> ConfirmationView : confirm()
RestartGameController --> StartGameController

PlayController --> GameView
note on link: readAction

@enduml