@startuml UCAnalysis_StartGame

mix_actor Player

package views {
  class GameView
  class MenuView
  class BoardView
  BoardView -right[hidden]-> MenuView 
}

package controllers {
    class PlayController
    class StartGameController
    PlayController *-right-> StartGameController

}

package models {
    class Deck
    class Waste
    class Foundation
    class Tableau
    class Card
    Deck -right[hidden]-> Waste
    Waste -right[hidden]-> Foundation
    Foundation -right[hidden]-> Tableau
    Tableau -right[hidden]-> Card
}

Player -down-> GameView
note on link: Select action

PlayController --> GameView
note on link: readAction()

StartGameController ..> Card
StartGameController -right-> Tableau: \n*new()\n*putCard()\n*FlipLastCard()
StartGameController --> Waste: \n*new()\n*getCard()
StartGameController --> Foundation: new()
StartGameController --> Deck: \n*new()\n*suffle()

StartGameController --> GameView : show()
GameView --> BoardView : show()
GameView --> MenuView : show()

@enduml