@startuml Views
class StartView{
    +showWelcome()
}

class OpenGameView {
    +getOrigin()
    +getTarget()
    +getRestart()
    +getExit()
    +getHelp()
    +getHint()
    +onError()
    +showGame()
 }

class ClosedGameView {
    getRestart()
    getExit()
}
@enduml

@startuml Controllers
class StartController{
    Game
    run()
    -initGame()
}

StartController --> StartView
PlayController --> PlayView
ClosedGameController --> ClosedGameView

class PlayController{
    Game
    run()
}

class ClosedGameController{
    run()
    -resetGame()
}
@enduml