@startuml
hide empty description

state "**StartGame**" as StartGame_origin
state a <<choice>> 

StartGame_origin -down-> OpenGame: startGame
OpenGame -down-> a : Move
a --> ClosedGame : isFinished
a --> OpenGame
OpenGame --> StartGame_origin : Restart
ClosedGame -up-> StartGame_origin : Play Again
@enduml
