@startuml States
hide empty description

state a <<choice>> 

state "**CLOSED_GAME**" as CLOSED_GAME
state "**OPEN_GAME**" as OPEN_GAME

CLOSED_GAME -down[hidden]-> OPEN_GAME
[*] -down-> CLOSED_GAME : Player runs the application
CLOSED_GAME --> OPEN_GAME : StartGame

OPEN_GAME --> [*]: ExitGame
OPEN_GAME -up-> OPEN_GAME : \n*ReStartGame\n*MoveFromDeckToWaste\n*MoveFromWasteToTableau\n*MoveFromTableauToTableau\n*FlipCardFromDeck
OPEN_GAME -left-> a : \n*MoveFromWasteToFoundation\n*MoveFromTableauToFoundation

note left of a
    [is Foundation complete?]
end note

a -right-> OPEN_GAME
a -right-> CLOSED_GAME : True
CLOSED_GAME -right-> [*] : ExitGame

@enduml
