@startuml
state choice1 <<choice>> 
state choice2 <<choice>>
state choice3 <<choice>> 

hide empty description 
state "Player select card to Move from a Tableau" as 1
state "Player select a Foundation as destination" as 2
state "Board is updated" as 3
OpenGame --> 1

1 --> choice1
choice1 --> 2: Selected card can be move
choice1 --> ShowError : Selected card cannot be move

2-down-> choice2
choice2 --> ShowError : selected Card cannot be move to the selected Foundation
choice2 --> 3: Foundation can receive Card
3--> choice3
choice3 --> Win: All foundations complete
choice3 --> OpenGame: Foundation not complete
ShowError --> OpenGame
@enduml
